### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by jorrel6130** [MikeTheNose/SystemAnalysisProject#5]
Pick any TEN (10) use cases from your project and create Written Use Cases
at the Kite Level (bird-eye view, use the template in chapter7 of the text book
(fig 7-32, 7-34 on page 226/228).

**Comment by Painkills** [comment]
Kite Level Use Case Diagrams I'll do:
Recall patients
Note Patient Data

**Comment by Painkills** [comment]
Recall patients and Note Patient Data done and uploaded.

**Comment by jorrel6130** [comment]
I'll do "book, cancel or reschedule an appointment" and  "jump wait line"
